### PR TITLE
MNT: rerender

### LINKED ISSUE #82: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #82.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #82

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@isuruf @beckermr, I think I'm missing something w.r.t. to CUDA 11.0. Do we need to do something special with regards to GLIBC or compiler version now? It seems Conda is having trouble finding build tools that would work here. Sorry I know there have been a lot of PRs recently around this, but have been out for the last couple weeks. So not entirely sure what we should be doing here. Any advice would be welcome 🙂

**Comment by isuruf** [comment]
You need to resend that cdt_name PR to the pinnings feedstock

**Comment by jakirkham** [comment]
Ah ok. Can do. Was unsure if that was already handled a different way. Thanks Isuru! 😄

**Comment by beckermr** [comment]
You can add cdt_name to the local conda build config too. However the pinnings pr coupling cdt name should work with the latest conda smithy.

**Comment by jakirkham** [comment]
Ok thanks. Have submitted as PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1076 ).

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Pull request merged**
