### PR TITLE
Skip CUDA 11.2.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The CUDA 11.8 migration in #137 and subsequent updates in #138 / #139 are producing two CUDA 11 packages, one from 11.2 and one from 11.8. This PR skips CUDA 11.2 since its outputs are functionally equivalent to those from CUDA 11.8. This equivalency was tested by @vyasr.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
We had the same discussion for NCCL (conda-forge/nccl-feedstock#102), and John wanted to keep 11.2.

**Comment by bdice** [comment]
Hmm. I’m not sure what difference we expect for ucx, if any, but currently there is no way to select between the two CUDA 11 packages except by hash.

**Comment by leofang** [comment]
Bradley, any chance you could do a quick grep and see if UCX has any usage on `CUDA_VERSION` etc at build time? I would support pruning the CI jobs (I asked the same for NCCL and more generally everywhere; when I asked for the migrator I didn't anticipate still keeping 11.2 around).

**Comment by bdice** [comment]
@wence- did an analysis of `ucx` and believes that it should be safe to use packages built with CUDA 11.8 on CUDA 11.2. That means this should be okay to merge.

**Comment by bdice** [comment]
@pentschev Great, thank you! I think we need a review from a maintainer. @quasiben or @leofang could you approve and merge? I think there is good consensus that this is the right move forward.

**Review by leofang — APPROVED** [review]
Thx guys, plz kindly send an admin request to remove erroneous packages uploaded in previous PRs when you get a chance.

**Comment by bdice** [comment]
@leofang Of course! Here: https://github.com/conda-forge/admin-requests/pull/824

**Comment by jakirkham** [comment]
Am noticing that we still have a lower bound of CUDA 11.2 here even though we are building against CUDA 11.8

https://github.com/conda-forge/ucx-split-feedstock/blob/3a288c14afdd01145d853cbff1c3e5f2bb2f5a21/recipe/meta.yaml#L39-L40

Is this expected?

Please let me know if there is more context I'm missing here

**Pull request merged**
